
Passed: 0 Failed: 0 Skipped: 0 (test/assignment/associativity.lox)
Passed: 1 Failed: 0 Skipped: 0 (test/assignment/global.lox)
Passed: 2 Failed: 0 Skipped: 0 (test/assignment/grouping.lox)
Passed: 3 Failed: 0 Skipped: 0 (test/assignment/infix_operator.lox)
Passed: 4 Failed: 0 Skipped: 0 (test/assignment/local.lox)
Passed: 5 Failed: 0 Skipped: 0 (test/assignment/prefix_operator.lox)
Passed: 6 Failed: 0 Skipped: 0 (test/assignment/syntax.lox)
Passed: 7 Failed: 0 Skipped: 0 (test/assignment/to_this.lox)
FAIL test/assignment/to_this.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 65 and got 101. Stderr:
     [line 3] Error at '=': Invalid assignment target.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 7 Failed: 1 Skipped: 0 (test/assignment/undefined.lox)
Passed: 8 Failed: 1 Skipped: 0 (test/block/empty.lox)
Passed: 9 Failed: 1 Skipped: 0 (test/block/scope.lox)
Passed: 10 Failed: 1 Skipped: 0 (test/bool/equality.lox)
Passed: 11 Failed: 1 Skipped: 0 (test/bool/not.lox)
Passed: 12 Failed: 1 Skipped: 0 (test/call/bool.lox)
Passed: 13 Failed: 1 Skipped: 0 (test/call/nil.lox)
Passed: 14 Failed: 1 Skipped: 0 (test/call/num.lox)
Passed: 15 Failed: 1 Skipped: 0 (test/call/object.lox)
Passed: 16 Failed: 1 Skipped: 0 (test/call/string.lox)
Passed: 17 Failed: 1 Skipped: 0 (test/class/empty.lox)
Passed: 18 Failed: 1 Skipped: 0 (test/class/inherit_self.lox)
FAIL test/class/inherit_self.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 65 and got 101. Stderr:
     [line 1] Error at 'Foo': A class can't inherit from itself.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 18 Failed: 2 Skipped: 0 (test/class/inherited_method.lox)
FAIL test/class/inherited_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'in foo' on line 20.
     Missing expected output 'in bar' on line 21.
     Missing expected output 'in baz' on line 22.


Passed: 18 Failed: 3 Skipped: 0 (test/class/local_inherit_other.lox)
FAIL test/class/local_inherit_other.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'B' on line 8.


Passed: 18 Failed: 4 Skipped: 0 (test/class/local_inherit_self.lox)
FAIL test/class/local_inherit_self.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected error: [5] Error at end: Expect '}' after block.
     Expected return code 65 and got 101. Stderr:
     [line 2] Error at 'Foo': A class can't inherit from itself.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 18 Failed: 5 Skipped: 0 (test/class/local_reference_self.lox)
FAIL test/class/local_reference_self.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Foo' on line 8.


Passed: 18 Failed: 6 Skipped: 0 (test/class/reference_self.lox)
FAIL test/class/reference_self.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Foo' on line 7.


Passed: 18 Failed: 7 Skipped: 0 (test/closure/assign_to_closure.lox)
Passed: 19 Failed: 7 Skipped: 0 (test/closure/assign_to_shadowed_later.lox)
Passed: 20 Failed: 7 Skipped: 0 (test/closure/close_over_function_parameter.lox)
Passed: 21 Failed: 7 Skipped: 0 (test/closure/close_over_later_variable.lox)
Passed: 22 Failed: 7 Skipped: 0 (test/closure/close_over_method_parameter.lox)
FAIL test/closure/close_over_method_parameter.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'param' on line 13.


Passed: 22 Failed: 8 Skipped: 0 (test/closure/closed_closure_in_function.lox)
Passed: 23 Failed: 8 Skipped: 0 (test/closure/nested_closure.lox)
Passed: 24 Failed: 8 Skipped: 0 (test/closure/open_closure_in_function.lox)
Passed: 25 Failed: 8 Skipped: 0 (test/closure/reference_closure_multiple_times.lox)
Passed: 26 Failed: 8 Skipped: 0 (test/closure/reuse_closure_slot.lox)
Passed: 27 Failed: 8 Skipped: 0 (test/closure/shadow_closure_with_local.lox)
Passed: 28 Failed: 8 Skipped: 0 (test/closure/unused_closure.lox)
Passed: 29 Failed: 8 Skipped: 0 (test/closure/unused_later_closure.lox)
Passed: 30 Failed: 8 Skipped: 0 (test/comments/line_at_eof.lox)
Passed: 31 Failed: 8 Skipped: 0 (test/comments/only_line_comment.lox)
Passed: 32 Failed: 8 Skipped: 0 (test/comments/only_line_comment_and_line.lox)
Passed: 33 Failed: 8 Skipped: 0 (test/comments/unicode.lox)
Passed: 34 Failed: 8 Skipped: 0 (test/constructor/arguments.lox)
FAIL test/constructor/arguments.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'init' on line 3.
     Missing expected output '1' on line 10.
     Missing expected output '2' on line 11.


Passed: 34 Failed: 9 Skipped: 0 (test/constructor/call_init_early_return.lox)
FAIL test/constructor/call_init_early_return.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'init' on line 9.
     Missing expected output 'init' on line 10.
     Missing expected output 'Foo instance' on line 11.


Passed: 34 Failed: 10 Skipped: 0 (test/constructor/call_init_explicitly.lox)
FAIL test/constructor/call_init_explicitly.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Foo.init(one)' on line 8.
     Missing expected output 'Foo.init(two)' on line 11.
     Missing expected output 'Foo instance' on line 12.
     Missing expected output 'init' on line 15.


Passed: 34 Failed: 11 Skipped: 0 (test/constructor/default.lox)
Passed: 35 Failed: 11 Skipped: 0 (test/constructor/default_arguments.lox)
FAIL test/constructor/default_arguments.lox
     Expected runtime error 'Expected 0 arguments but got 3.' and got none.
     Expected return code 70 and got 0. Stderr:


Passed: 35 Failed: 12 Skipped: 0 (test/constructor/early_return.lox)
FAIL test/constructor/early_return.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'init' on line 9.
     Missing expected output 'Foo instance' on line 10.


Passed: 35 Failed: 13 Skipped: 0 (test/constructor/extra_arguments.lox)
FAIL test/constructor/extra_arguments.lox
     Expected runtime error 'Expected 2 arguments but got 4.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 35 Failed: 14 Skipped: 0 (test/constructor/init_not_method.lox)
FAIL test/constructor/init_not_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'not initializer' on line 12.


Passed: 35 Failed: 15 Skipped: 0 (test/constructor/missing_arguments.lox)
FAIL test/constructor/missing_arguments.lox
     Expected runtime error 'Expected 2 arguments but got 1.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 35 Failed: 16 Skipped: 0 (test/constructor/return_in_nested_function.lox)
FAIL test/constructor/return_in_nested_function.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'bar' on line 6.
     Missing expected output 'Foo instance' on line 10.


Passed: 35 Failed: 17 Skipped: 0 (test/constructor/return_value.lox)
FAIL test/constructor/return_value.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 65 and got 101. Stderr:
     [line 3] Error at 'return': Can't return a value from an initializer.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 35 Failed: 18 Skipped: 0 (test/empty_file.lox)
Passed: 36 Failed: 18 Skipped: 0 (test/expressions/evaluate.lox)
Passed: 36 Failed: 18 Skipped: 1 (test/expressions/parse.lox)
Passed: 36 Failed: 18 Skipped: 2 (test/field/call_function_field.lox)
FAIL test/field/call_function_field.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'bar' on line 13.
     Missing expected output '1' on line 14.
     Missing expected output '2' on line 15.


Passed: 36 Failed: 19 Skipped: 2 (test/field/call_nonfunction_field.lox)
FAIL test/field/call_nonfunction_field.lox
     Expected runtime error 'Can only call functions and classes.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 36 Failed: 20 Skipped: 2 (test/field/get_and_set_method.lox)
FAIL test/field/get_and_set_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'other' on line 19.
     Missing expected output '1' on line 20.
     Missing expected output 'method' on line 24.
     Missing expected output '2' on line 25.


Passed: 36 Failed: 21 Skipped: 2 (test/field/get_on_bool.lox)
FAIL test/field/get_on_bool.lox
     Expected runtime error 'Only instances have properties.' and got:
     Only instances have fields.


Passed: 36 Failed: 22 Skipped: 2 (test/field/get_on_class.lox)
FAIL test/field/get_on_class.lox
     Expected runtime error 'Only instances have properties.' and got:
     Only instances have fields.


Passed: 36 Failed: 23 Skipped: 2 (test/field/get_on_function.lox)
FAIL test/field/get_on_function.lox
     Expected runtime error 'Only instances have properties.' and got:
     Only instances have fields.


Passed: 36 Failed: 24 Skipped: 2 (test/field/get_on_nil.lox)
FAIL test/field/get_on_nil.lox
     Expected runtime error 'Only instances have properties.' and got:
     Only instances have fields.


Passed: 36 Failed: 25 Skipped: 2 (test/field/get_on_num.lox)
FAIL test/field/get_on_num.lox
     Expected runtime error 'Only instances have properties.' and got:
     Only instances have fields.


Passed: 36 Failed: 26 Skipped: 2 (test/field/get_on_string.lox)
FAIL test/field/get_on_string.lox
     Expected runtime error 'Only instances have properties.' and got:
     Only instances have fields.


Passed: 36 Failed: 27 Skipped: 2 (test/field/many.lox)
Passed: 37 Failed: 27 Skipped: 2 (test/field/method.lox)
FAIL test/field/method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'got method' on line 8.
     Missing expected output 'arg' on line 9.


Passed: 37 Failed: 28 Skipped: 2 (test/field/method_binds_this.lox)
FAIL test/field/method_binds_this.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'foo1' on line 18.
     Missing expected output '1' on line 19.


Passed: 37 Failed: 29 Skipped: 2 (test/field/on_instance.lox)
Passed: 38 Failed: 29 Skipped: 2 (test/field/set_evaluation_order.lox)
Passed: 39 Failed: 29 Skipped: 2 (test/field/set_on_bool.lox)
Passed: 40 Failed: 29 Skipped: 2 (test/field/set_on_class.lox)
Passed: 41 Failed: 29 Skipped: 2 (test/field/set_on_function.lox)
Passed: 42 Failed: 29 Skipped: 2 (test/field/set_on_nil.lox)
Passed: 43 Failed: 29 Skipped: 2 (test/field/set_on_num.lox)
Passed: 44 Failed: 29 Skipped: 2 (test/field/set_on_string.lox)
Passed: 45 Failed: 29 Skipped: 2 (test/field/undefined.lox)
FAIL test/field/undefined.lox
     Expected runtime error 'Undefined property 'bar'.' and got:
     Undefined property bar.


Passed: 45 Failed: 30 Skipped: 2 (test/for/class_in_body.lox)
Passed: 46 Failed: 30 Skipped: 2 (test/for/closure_in_body.lox)
Passed: 47 Failed: 30 Skipped: 2 (test/for/fun_in_body.lox)
Passed: 48 Failed: 30 Skipped: 2 (test/for/return_closure.lox)
Passed: 49 Failed: 30 Skipped: 2 (test/for/return_inside.lox)
Passed: 50 Failed: 30 Skipped: 2 (test/for/scope.lox)
Passed: 51 Failed: 30 Skipped: 2 (test/for/statement_condition.lox)
Passed: 52 Failed: 30 Skipped: 2 (test/for/statement_increment.lox)
Passed: 53 Failed: 30 Skipped: 2 (test/for/statement_initializer.lox)
Passed: 54 Failed: 30 Skipped: 2 (test/for/syntax.lox)
Passed: 55 Failed: 30 Skipped: 2 (test/for/var_in_body.lox)
Passed: 56 Failed: 30 Skipped: 2 (test/function/body_must_be_block.lox)
Passed: 57 Failed: 30 Skipped: 2 (test/function/empty_body.lox)
Passed: 58 Failed: 30 Skipped: 2 (test/function/extra_arguments.lox)
Passed: 59 Failed: 30 Skipped: 2 (test/function/local_mutual_recursion.lox)
Passed: 60 Failed: 30 Skipped: 2 (test/function/local_recursion.lox)
Passed: 61 Failed: 30 Skipped: 2 (test/function/missing_arguments.lox)
Passed: 62 Failed: 30 Skipped: 2 (test/function/missing_comma_in_parameters.lox)
Passed: 63 Failed: 30 Skipped: 2 (test/function/mutual_recursion.lox)
Passed: 64 Failed: 30 Skipped: 2 (test/function/nested_call_with_arguments.lox)
Passed: 65 Failed: 30 Skipped: 2 (test/function/parameters.lox)
Passed: 66 Failed: 30 Skipped: 2 (test/function/print.lox)
Passed: 67 Failed: 30 Skipped: 2 (test/function/recursion.lox)
Passed: 68 Failed: 30 Skipped: 2 (test/function/too_many_arguments.lox)
Passed: 69 Failed: 30 Skipped: 2 (test/function/too_many_parameters.lox)
Passed: 70 Failed: 30 Skipped: 2 (test/if/class_in_else.lox)
Passed: 71 Failed: 30 Skipped: 2 (test/if/class_in_then.lox)
Passed: 72 Failed: 30 Skipped: 2 (test/if/dangling_else.lox)
Passed: 73 Failed: 30 Skipped: 2 (test/if/else.lox)
Passed: 74 Failed: 30 Skipped: 2 (test/if/fun_in_else.lox)
Passed: 75 Failed: 30 Skipped: 2 (test/if/fun_in_then.lox)
Passed: 76 Failed: 30 Skipped: 2 (test/if/if.lox)
Passed: 77 Failed: 30 Skipped: 2 (test/if/truth.lox)
Passed: 78 Failed: 30 Skipped: 2 (test/if/var_in_else.lox)
Passed: 79 Failed: 30 Skipped: 2 (test/if/var_in_then.lox)
Passed: 80 Failed: 30 Skipped: 2 (test/inheritance/constructor.lox)
FAIL test/inheritance/constructor.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'value' on line 14.


Passed: 80 Failed: 31 Skipped: 2 (test/inheritance/inherit_from_function.lox)
FAIL test/inheritance/inherit_from_function.lox
     Expected runtime error 'Superclass must be a class.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 80 Failed: 32 Skipped: 2 (test/inheritance/inherit_from_nil.lox)
FAIL test/inheritance/inherit_from_nil.lox
     Expected runtime error 'Superclass must be a class.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 80 Failed: 33 Skipped: 2 (test/inheritance/inherit_from_number.lox)
FAIL test/inheritance/inherit_from_number.lox
     Expected runtime error 'Superclass must be a class.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 80 Failed: 34 Skipped: 2 (test/inheritance/inherit_methods.lox)
FAIL test/inheritance/inherit_methods.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'foo' on line 12.
     Missing expected output 'bar' on line 13.
     Missing expected output 'bar' on line 14.


Passed: 80 Failed: 35 Skipped: 2 (test/inheritance/parenthesized_superclass.lox)
FAIL test/inheritance/parenthesized_superclass.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 65 and got 101. Stderr:
     [line 4] Error at '(': Expect superclass name.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 80 Failed: 36 Skipped: 2 (test/inheritance/set_fields_from_base_class.lox)
FAIL test/inheritance/set_fields_from_base_class.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'foo 1' on line 28.
     Missing expected output 'foo 2' on line 29.
     Missing expected output 'bar 1' on line 33.
     Missing expected output 'bar 2' on line 34.
     Missing expected output 'bar 1' on line 37.
     Missing expected output 'bar 2' on line 38.


Passed: 80 Failed: 37 Skipped: 2 (test/limit/loop_too_large.lox)
FAIL test/limit/loop_too_large.lox
     Missing expected error: [2351] Error at '}': Loop body too large.
     Expected return code 65 and got 0. Stderr:


Passed: 80 Failed: 38 Skipped: 2 (test/limit/no_reuse_constants.lox)
FAIL test/limit/no_reuse_constants.lox
     Missing expected error: [35] Error at '1': Too many constants in one chunk.
     Expected return code 65 and got 0. Stderr:


Passed: 80 Failed: 39 Skipped: 2 (test/limit/stack_overflow.lox)
Passed: 81 Failed: 39 Skipped: 2 (test/limit/too_many_constants.lox)
FAIL test/limit/too_many_constants.lox
     Missing expected error: [35] Error at '"oops"': Too many constants in one chunk.
     Expected return code 65 and got 0. Stderr:


Passed: 81 Failed: 40 Skipped: 2 (test/limit/too_many_locals.lox)
Passed: 82 Failed: 40 Skipped: 2 (test/limit/too_many_upvalues.lox)
Passed: 83 Failed: 40 Skipped: 2 (test/logical_operator/and.lox)
Passed: 84 Failed: 40 Skipped: 2 (test/logical_operator/and_truth.lox)
Passed: 85 Failed: 40 Skipped: 2 (test/logical_operator/or.lox)
Passed: 86 Failed: 40 Skipped: 2 (test/logical_operator/or_truth.lox)
Passed: 87 Failed: 40 Skipped: 2 (test/method/arity.lox)
FAIL test/method/arity.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'no args' on line 14.
     Missing expected output '1' on line 15.
     Missing expected output '3' on line 16.
     Missing expected output '6' on line 17.
     Missing expected output '10' on line 18.
     Missing expected output '15' on line 19.
     Missing expected output '21' on line 20.
     Missing expected output '28' on line 21.
     Missing expected output '36' on line 22.


Passed: 87 Failed: 41 Skipped: 2 (test/method/empty_block.lox)
FAIL test/method/empty_block.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'nil' on line 5.


Passed: 87 Failed: 42 Skipped: 2 (test/method/extra_arguments.lox)
FAIL test/method/extra_arguments.lox
     Expected runtime error 'Expected 2 arguments but got 4.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 87 Failed: 43 Skipped: 2 (test/method/missing_arguments.lox)
FAIL test/method/missing_arguments.lox
     Expected runtime error 'Expected 2 arguments but got 1.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 87 Failed: 44 Skipped: 2 (test/method/not_found.lox)
FAIL test/method/not_found.lox
     Expected runtime error 'Undefined property 'unknown'.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 87 Failed: 45 Skipped: 2 (test/method/print_bound_method.lox)
FAIL test/method/print_bound_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output '<fn method>' on line 5.


Passed: 87 Failed: 46 Skipped: 2 (test/method/refer_to_name.lox)
FAIL test/method/refer_to_name.lox
     Expected runtime error 'Undefined variable 'method'.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 87 Failed: 47 Skipped: 2 (test/method/too_many_arguments.lox)
FAIL test/method/too_many_arguments.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 65 and got 101. Stderr:
     [line 259] Error at 'a': Can't have more than 255 arguments.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 87 Failed: 48 Skipped: 2 (test/method/too_many_parameters.lox)
FAIL test/method/too_many_parameters.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 65 and got 101. Stderr:
     [line 258] Error at 'a': Can't have more than 255 parameters.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 87 Failed: 49 Skipped: 2 (test/nil/literal.lox)
Passed: 88 Failed: 49 Skipped: 2 (test/number/decimal_point_at_eof.lox)
Passed: 89 Failed: 49 Skipped: 2 (test/number/leading_dot.lox)
Passed: 90 Failed: 49 Skipped: 2 (test/number/literals.lox)
Passed: 91 Failed: 49 Skipped: 2 (test/number/nan_equality.lox)
Passed: 92 Failed: 49 Skipped: 2 (test/number/trailing_dot.lox)
Passed: 93 Failed: 49 Skipped: 2 (test/operator/add.lox)
Passed: 94 Failed: 49 Skipped: 2 (test/operator/add_bool_nil.lox)
Passed: 95 Failed: 49 Skipped: 2 (test/operator/add_bool_num.lox)
Passed: 96 Failed: 49 Skipped: 2 (test/operator/add_bool_string.lox)
Passed: 97 Failed: 49 Skipped: 2 (test/operator/add_nil_nil.lox)
Passed: 98 Failed: 49 Skipped: 2 (test/operator/add_num_nil.lox)
Passed: 99 Failed: 49 Skipped: 2 (test/operator/add_string_nil.lox)
Passed: 100 Failed: 49 Skipped: 2 (test/operator/comparison.lox)
Passed: 101 Failed: 49 Skipped: 2 (test/operator/divide.lox)
Passed: 102 Failed: 49 Skipped: 2 (test/operator/divide_nonnum_num.lox)
Passed: 103 Failed: 49 Skipped: 2 (test/operator/divide_num_nonnum.lox)
Passed: 104 Failed: 49 Skipped: 2 (test/operator/equals.lox)
Passed: 105 Failed: 49 Skipped: 2 (test/operator/equals_class.lox)
Passed: 106 Failed: 49 Skipped: 2 (test/operator/equals_method.lox)
FAIL test/operator/equals_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'true' on line 10.
     Missing expected output 'false' on line 13.


Passed: 106 Failed: 50 Skipped: 2 (test/operator/greater_nonnum_num.lox)
Passed: 107 Failed: 50 Skipped: 2 (test/operator/greater_num_nonnum.lox)
Passed: 108 Failed: 50 Skipped: 2 (test/operator/greater_or_equal_nonnum_num.lox)
Passed: 109 Failed: 50 Skipped: 2 (test/operator/greater_or_equal_num_nonnum.lox)
Passed: 110 Failed: 50 Skipped: 2 (test/operator/less_nonnum_num.lox)
Passed: 111 Failed: 50 Skipped: 2 (test/operator/less_num_nonnum.lox)
Passed: 112 Failed: 50 Skipped: 2 (test/operator/less_or_equal_nonnum_num.lox)
Passed: 113 Failed: 50 Skipped: 2 (test/operator/less_or_equal_num_nonnum.lox)
Passed: 114 Failed: 50 Skipped: 2 (test/operator/multiply.lox)
Passed: 115 Failed: 50 Skipped: 2 (test/operator/multiply_nonnum_num.lox)
Passed: 116 Failed: 50 Skipped: 2 (test/operator/multiply_num_nonnum.lox)
Passed: 117 Failed: 50 Skipped: 2 (test/operator/negate.lox)
Passed: 118 Failed: 50 Skipped: 2 (test/operator/negate_nonnum.lox)
Passed: 119 Failed: 50 Skipped: 2 (test/operator/not.lox)
Passed: 120 Failed: 50 Skipped: 2 (test/operator/not_class.lox)
Passed: 121 Failed: 50 Skipped: 2 (test/operator/not_equals.lox)
Passed: 122 Failed: 50 Skipped: 2 (test/operator/subtract.lox)
Passed: 123 Failed: 50 Skipped: 2 (test/operator/subtract_nonnum_num.lox)
Passed: 124 Failed: 50 Skipped: 2 (test/operator/subtract_num_nonnum.lox)
Passed: 125 Failed: 50 Skipped: 2 (test/precedence.lox)
Passed: 126 Failed: 50 Skipped: 2 (test/print/missing_argument.lox)
Passed: 127 Failed: 50 Skipped: 2 (test/regression/394.lox)
FAIL test/regression/394.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'B' on line 4.


Passed: 127 Failed: 51 Skipped: 2 (test/regression/40.lox)
Passed: 128 Failed: 51 Skipped: 2 (test/return/after_else.lox)
Passed: 129 Failed: 51 Skipped: 2 (test/return/after_if.lox)
Passed: 130 Failed: 51 Skipped: 2 (test/return/after_while.lox)
Passed: 131 Failed: 51 Skipped: 2 (test/return/at_top_level.lox)
Passed: 132 Failed: 51 Skipped: 2 (test/return/in_function.lox)
Passed: 133 Failed: 51 Skipped: 2 (test/return/in_method.lox)
FAIL test/return/in_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'ok' on line 8.


Passed: 133 Failed: 52 Skipped: 2 (test/return/return_nil_if_no_value.lox)
Passed: 134 Failed: 52 Skipped: 2 (test/scanning/identifiers.lox)
Passed: 134 Failed: 52 Skipped: 3 (test/scanning/keywords.lox)
Passed: 134 Failed: 52 Skipped: 4 (test/scanning/numbers.lox)
Passed: 134 Failed: 52 Skipped: 5 (test/scanning/punctuators.lox)
Passed: 134 Failed: 52 Skipped: 6 (test/scanning/strings.lox)
Passed: 134 Failed: 52 Skipped: 7 (test/scanning/whitespace.lox)
Passed: 134 Failed: 52 Skipped: 8 (test/string/error_after_multiline.lox)
Passed: 135 Failed: 52 Skipped: 8 (test/string/literals.lox)
Passed: 136 Failed: 52 Skipped: 8 (test/string/multiline.lox)
Passed: 137 Failed: 52 Skipped: 8 (test/string/unterminated.lox)
Passed: 138 Failed: 52 Skipped: 8 (test/super/bound_method.lox)
FAIL test/super/bound_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'A.method(arg)' on line 19.


Passed: 138 Failed: 53 Skipped: 8 (test/super/call_other_method.lox)
FAIL test/super/call_other_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Derived.bar()' on line 15.
     Missing expected output 'Base.foo()' on line 16.


Passed: 138 Failed: 54 Skipped: 8 (test/super/call_same_method.lox)
FAIL test/super/call_same_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Derived.foo()' on line 15.
     Missing expected output 'Base.foo()' on line 16.


Passed: 138 Failed: 55 Skipped: 8 (test/super/closure.lox)
FAIL test/super/closure.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Base' on line 17.


Passed: 138 Failed: 56 Skipped: 8 (test/super/constructor.lox)
FAIL test/super/constructor.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Derived.init()' on line 15.
     Missing expected output 'Base.init(a, b)' on line 16.


Passed: 138 Failed: 57 Skipped: 8 (test/super/extra_arguments.lox)
FAIL test/super/extra_arguments.lox
     Expected runtime error 'Expected 2 arguments but got 4.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Derived.foo()' on line 9.


Passed: 138 Failed: 58 Skipped: 8 (test/super/indirectly_inherited.lox)
FAIL test/super/indirectly_inherited.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'C.foo()' on line 17.
     Missing expected output 'A.foo()' on line 18.


Passed: 138 Failed: 59 Skipped: 8 (test/super/missing_arguments.lox)
FAIL test/super/missing_arguments.lox
     Expected runtime error 'Expected 2 arguments but got 1.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 60 Skipped: 8 (test/super/no_superclass_bind.lox)
FAIL test/super/no_superclass_bind.lox
     Unexpected error:
     [line 3] Error at 'super': Can't use 'super' outside of a class.
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected error: [3] Error at 'super': Can't use 'super' in a class with no superclass.
     Expected return code 65 and got 101. Stderr:
     [line 3] Error at 'super': Can't use 'super' outside of a class.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 61 Skipped: 8 (test/super/no_superclass_call.lox)
FAIL test/super/no_superclass_call.lox
     Unexpected error:
     [line 3] Error at 'super': Can't use 'super' outside of a class.
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected error: [3] Error at 'super': Can't use 'super' in a class with no superclass.
     Expected return code 65 and got 101. Stderr:
     [line 3] Error at 'super': Can't use 'super' outside of a class.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 62 Skipped: 8 (test/super/no_superclass_method.lox)
FAIL test/super/no_superclass_method.lox
     Expected runtime error 'Undefined property 'doesNotExist'.' and got:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Expected stack trace and got:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 70 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 63 Skipped: 8 (test/super/parenthesized.lox)
FAIL test/super/parenthesized.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected error: [8] Error at ')': Expect '.' after 'super'.
     Expected return code 65 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 64 Skipped: 8 (test/super/reassign_superclass.lox)
FAIL test/super/reassign_superclass.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Base.method()' on line 20.
     Missing expected output 'Base.method()' on line 22.


Passed: 138 Failed: 65 Skipped: 8 (test/super/super_at_top_level.lox)
FAIL test/super/super_at_top_level.lox
     Unexpected error:
     [line 1] Error at 'super': Can't use 'super' in a class with no superclass.
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected error: [1] Error at 'super': Can't use 'super' outside of a class.
     Missing expected error: [2] Error at 'super': Can't use 'super' outside of a class.
     Expected return code 65 and got 101. Stderr:
     [line 1] Error at 'super': Can't use 'super' in a class with no superclass.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 66 Skipped: 8 (test/super/super_in_closure_in_inherited_method.lox)
FAIL test/super/super_in_closure_in_inherited_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'A' on line 26.


Passed: 138 Failed: 67 Skipped: 8 (test/super/super_in_inherited_method.lox)
FAIL test/super/super_in_inherited_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'A' on line 23.


Passed: 138 Failed: 68 Skipped: 8 (test/super/super_in_top_level_function.lox)
FAIL test/super/super_in_top_level_function.lox
     Unexpected error:
     [line 1] Error at 'super': Can't use 'super' in a class with no superclass.
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected error: [1] Error at 'super': Can't use 'super' outside of a class.
     Expected return code 65 and got 101. Stderr:
     [line 1] Error at 'super': Can't use 'super' in a class with no superclass.
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 69 Skipped: 8 (test/super/super_without_dot.lox)
FAIL test/super/super_without_dot.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected error: [6] Error at ';': Expect '.' after 'super'.
     Expected return code 65 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 70 Skipped: 8 (test/super/super_without_name.lox)
FAIL test/super/super_without_name.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected error: [5] Error at ';': Expect superclass method name.
     Expected return code 65 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Passed: 138 Failed: 71 Skipped: 8 (test/super/this_in_superclass_method.lox)
FAIL test/super/this_in_superclass_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'a' on line 15.
     Missing expected output 'b' on line 16.


Passed: 138 Failed: 72 Skipped: 8 (test/this/closure.lox)
FAIL test/this/closure.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Foo' on line 13.


Passed: 138 Failed: 73 Skipped: 8 (test/this/nested_class.lox)
FAIL test/this/nested_class.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Outer instance' on line 3.
     Missing expected output 'Outer instance' on line 6.
     Missing expected output 'Inner instance' on line 10.


Passed: 138 Failed: 74 Skipped: 8 (test/this/nested_closure.lox)
FAIL test/this/nested_closure.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'Foo' on line 19.


Passed: 138 Failed: 75 Skipped: 8 (test/this/this_at_top_level.lox)
Passed: 139 Failed: 75 Skipped: 8 (test/this/this_in_method.lox)
FAIL test/this/this_in_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'baz' on line 6.


Passed: 139 Failed: 76 Skipped: 8 (test/this/this_in_top_level_function.lox)
Passed: 140 Failed: 76 Skipped: 8 (test/unexpected_character.lox)
Passed: 141 Failed: 76 Skipped: 8 (test/variable/collide_with_parameter.lox)
Passed: 142 Failed: 76 Skipped: 8 (test/variable/duplicate_local.lox)
Passed: 143 Failed: 76 Skipped: 8 (test/variable/duplicate_parameter.lox)
Passed: 144 Failed: 76 Skipped: 8 (test/variable/early_bound.lox)
Passed: 145 Failed: 76 Skipped: 8 (test/variable/in_middle_of_block.lox)
Passed: 146 Failed: 76 Skipped: 8 (test/variable/in_nested_block.lox)
Passed: 147 Failed: 76 Skipped: 8 (test/variable/local_from_method.lox)
FAIL test/variable/local_from_method.lox
     Unexpected output on stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     Unexpected output on stderr:
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Expected return code 0 and got 101. Stderr:
     thread 'main' panicked at 'Should not be called while developing the compiler!', src/compiler.rs:465:9
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Missing expected output 'variable' on line 9.


Passed: 147 Failed: 77 Skipped: 8 (test/variable/redeclare_global.lox)
Passed: 148 Failed: 77 Skipped: 8 (test/variable/redefine_global.lox)
Passed: 149 Failed: 77 Skipped: 8 (test/variable/scope_reuse_in_different_blocks.lox)
Passed: 150 Failed: 77 Skipped: 8 (test/variable/shadow_and_local.lox)
Passed: 151 Failed: 77 Skipped: 8 (test/variable/shadow_global.lox)
Passed: 152 Failed: 77 Skipped: 8 (test/variable/shadow_local.lox)
Passed: 153 Failed: 77 Skipped: 8 (test/variable/undefined_global.lox)
Passed: 154 Failed: 77 Skipped: 8 (test/variable/undefined_local.lox)
Passed: 155 Failed: 77 Skipped: 8 (test/variable/uninitialized.lox)
Passed: 156 Failed: 77 Skipped: 8 (test/variable/unreached_undefined.lox)
Passed: 157 Failed: 77 Skipped: 8 (test/variable/use_false_as_var.lox)
Passed: 158 Failed: 77 Skipped: 8 (test/variable/use_global_in_initializer.lox)
Passed: 159 Failed: 77 Skipped: 8 (test/variable/use_local_in_initializer.lox)
Passed: 160 Failed: 77 Skipped: 8 (test/variable/use_nil_as_var.lox)
Passed: 161 Failed: 77 Skipped: 8 (test/variable/use_this_as_var.lox)
Passed: 162 Failed: 77 Skipped: 8 (test/while/class_in_body.lox)
Passed: 163 Failed: 77 Skipped: 8 (test/while/closure_in_body.lox)
Passed: 164 Failed: 77 Skipped: 8 (test/while/fun_in_body.lox)
Passed: 165 Failed: 77 Skipped: 8 (test/while/return_closure.lox)
Passed: 166 Failed: 77 Skipped: 8 (test/while/return_inside.lox)
Passed: 167 Failed: 77 Skipped: 8 (test/while/syntax.lox)
Passed: 168 Failed: 77 Skipped: 8 (test/while/var_in_body.lox)
169 tests passed. 77 tests failed.
